# Generated by Django 3.0.3 on 2020-02-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.facultad')),
            ],
        ),
    ]
