# Generated by Django 3.0.3 on 2020-02-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('usuarios', 'Permiso al modulo de usuarios'), ('academico', 'Permiso al modulo academico'))},
        ),
    ]
