# Generated by Django 3.0.3 on 2020-02-12 15:23

import apps.redicurri.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluacion_recurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(default=apps.redicurri.models.gestion, unique=True, verbose_name='Gestion')),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('director', models.CharField(blank=True, choices=[('t', 'Titular'), ('i', 'A ínterin')], max_length=2, null=True, verbose_name='Aplicar en caso de que la respuesta sea Director.')),
                ('aprobacion', models.DateField(verbose_name='Indique en qué fecha se aprobó el actual diseño curricular que está aplicando la carrera (RAN)')),
                ('retapa_1', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Jornada Académica?')),
                ('netapa_1', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_1', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('retapa_2', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Diagnostico Inicial?')),
                ('netapa_2', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_2', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('retapa_3', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Estudio de Contexto?')),
                ('netapa_3', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_3', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('retapa_4', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Mesa Multisectorial?')),
                ('netapa_4', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_4', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('retapa_5', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Macro Curricula?')),
                ('netapa_5', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_5', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('retapa_6', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Reunión Académica de la RAC?')),
                ('netapa_6', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_6', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('retapa_7', models.BooleanField(blank=True, verbose_name='La carrera realizo la etapa de Reunión Académica Nacional RAN')),
                ('netapa_7', models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa?')),
                ('oetapa_7', models.TextField(blank=True, null=True, verbose_name='Cuales otros?')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carrera')),
            ],
        ),
    ]
