# Generated by Django 3.0.3 on 2020-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_recurricular',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
