# Generated by Django 3.0.3 on 2020-02-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0002_evaluacion_recurricular_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapa_1',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('pregunta_1', models.BooleanField(verbose_name='1.1.\tEl Departamento de Gestión Curricular, programó con anticipación la jornada académica, cumpliendo con las etapas requeridas.')),
                ('pregunta_2', models.CharField(choices=[('c', 'Formación Basada en competencias'), ('po', 'Por objetivos'), ('o', 'Otros')], max_length=2, verbose_name='1.2.\tQué tipo de enfoque es el que se utilizó para el rediseño curricular. Elija una opción')),
                ('opregunta_2', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_3', models.BooleanField(verbose_name='1.3.\tSe realizaron exposiciones para la comprensión del proceso de rediseño curricular.')),
                ('pregunta_4', models.CharField(choices=[('b', 'Buena'), ('ra', 'Razonable'), ('re', 'Regular'), ('d', 'Deficiente')], max_length=2, verbose_name='1.4.\t¿La comprensión de la exposición de las etapas metodológicas del rediseño curricular fue? Elija una opción:')),
                ('pregunta_4_1', models.CharField(blank=True, choices=[('e', 'Excelente'), ('b', 'Buena'), ('ra', 'Razonable'), ('re', 'Regular'), ('d', 'Deficiente')], max_length=2, null=True, verbose_name='1.4.1.\tQué grado de comprensión se tuvo del enfoque para el rediseño curricular. Elija una opción:')),
                ('pregunta_4_2', models.CharField(blank=True, choices=[('e', 'Excelente'), ('b', 'Buena'), ('ra', 'Razonable')], max_length=2, null=True, verbose_name='1.4.2.\tUsted cree que el procedimiento empleado en el trabajo es. Elija una opción:')),
                ('pregunta_5', models.BooleanField(verbose_name='1.5.\tFue entregado por el Departamento de Gestión curricular, el material de apoyo o consulta.')),
                ('pregunta_6', models.CharField(choices=[('b', 'Computadora'), ('c', 'Celular'), ('d', 'Data Display'), ('o', 'Otros')], max_length=2, verbose_name='1.6.\tQue herramienta digital utilizó para organizar la información en esta etapa. Puede elegir varias opciones:')),
                ('opregunta_6', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_7', models.CharField(choices=[('b', 'Bueno'), ('o', 'Oportuno'), ('r', 'Regular')], max_length=2, verbose_name='1.7.\tQue calificación daría al equipo de gestión curricular en esta etapa.')),
            ],
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_1',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Jornada Académica)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_2',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Diagnostico Inicial)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_3',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Estudio de Contexto)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_4',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Mesa Multisectorial)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_5',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Macro Curricula)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_6',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Reunión Académica de la RAC)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_7',
            field=models.CharField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=2, null=True, verbose_name='Porque no realizó esta etapa? (Reunión Académica Nacional RAN)'),
        ),
    ]
