# Generated by Django 3.0.3 on 2020-02-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0003_auto_20200217_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapa_2',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
            ],
        ),
        migrations.RemoveField(
            model_name='etapa_1',
            name='pregunta_4_1',
        ),
        migrations.RemoveField(
            model_name='etapa_1',
            name='pregunta_4_2',
        ),
        migrations.AddField(
            model_name='etapa_1',
            name='sugpregunta_4',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AlterField(
            model_name='etapa_1',
            name='pregunta_3',
            field=models.BooleanField(verbose_name='1.3.\tSe realizaron exposiciones (departamento de gestión Curricular) para la comprensión del proceso de rediseño curricular'),
        ),
        migrations.AlterField(
            model_name='etapa_1',
            name='pregunta_5',
            field=models.BooleanField(verbose_name='1.5.\tSe necesitó ampliar la exposición de las etapas metodológicas del rediseño curricular'),
        ),
    ]
