# Generated by Django 3.0.3 on 2020-02-18 12:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0004_auto_20200217_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa_2',
            name='opregunta_12',
            field=models.TextField(blank=True, null=True, verbose_name='Que Otros?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='opregunta_13',
            field=models.TextField(blank=True, null=True, verbose_name='Que Otros?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_1',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.2.\tEl formulario FDI-1: documentos de creación, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_10',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.11. El formulario FDI-4a de pertinencia estudiantil, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_11',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.12. El formulario FDI-4b: cuestionario de pertinencia docente, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_12',
            field=models.CharField(choices=[('pp', 'Poca predisposición de los encuestados'), ('de', 'Demora en la entrega de las encuestas'), ('pc', 'Poca comprensión de los formularios'), ('o', 'Otros')], default='', max_length=2, verbose_name='2.13. Que dificultad tuvo al momento de hacer la recolección de información con los formularios antes mencionados. Seleccione Varias opciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_13',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('b', 'Computadora'), ('c', 'Celular'), ('d', 'Data Display'), ('o', 'Otros')], default='', max_length=2, verbose_name='1.6. Que herramienta digital utilizó para organizar la información en esta etapa. Puede elegir varias opciones:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_14',
            field=models.CharField(choices=[('b', 'Bueno'), ('o', 'Oportuno'), ('r', 'Regular')], default='', max_length=2, verbose_name='2.15. Que calificación daría al equipo de gestión curricular en esta etapa.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_2',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.3.\tEl formulario FDI-2: plan curricular vigente, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_3',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.4.\tEl formulario FDI-3a de componente docentes, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_4',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.5.\tEl formulario FDI-3b: componentes estudiantes, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_5',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.6.\tEl formulario FDI-3c: componente de interacción, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_6',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.7.\tEl formulario FDI-3d: componente de recursos educativos fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_7',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.8.\tEl formulario FDI-3e: administración financiera, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_8',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.9.\tEl formulario FDI-3f: componente de equipamiento, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='pregunta_9',
            field=models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], default=0, verbose_name='2.10. El formulario FDI-3g: seguimiento a graduados, fue.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_1',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_10',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_11',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_2',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_3',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_4',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_5',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_6',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_7',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_8',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
        migrations.AddField(
            model_name='etapa_2',
            name='sugpregunta_9',
            field=models.TextField(blank=True, null=True, verbose_name='Que sujiere?'),
        ),
    ]
