# Generated by Django 3.0.3 on 2020-02-18 15:14

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0008_auto_20200218_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapa_3',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('pregunta_1', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.2.\tEl formulario F-EC1; mapeo de actores institucionales e informantes fue.')),
                ('sugpregunta_1', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_2', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.3.\tEl formulario F-EC2, cuestionarios realizados a empleadores públicos y privados sirvieron para la obtención de resultados de manera.')),
                ('sugpregunta_2', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_3', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.4.\tEl formulario F-EC3, cuestionarios realizados a profesionales con empleo sirvieron para la obtención de resultados de manera.')),
                ('sugpregunta_3', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_4', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.5.\tEl formulario F-EC4, cuestionarios realizados a profesionales sin empleo sirvieron para la obtención de resultados de manera.')),
                ('sugpregunta_4', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_5', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.6.\tEl formulario F-EC5, entrevistas a expertos sirvió para la obtención de resultados de manera.')),
                ('sugpregunta_5', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_6', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.7.\tEl formulario F-EC6, análisis documental denota los requerimientos para el desarrollo del rediseño curricular, es.')),
                ('sugpregunta_6', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_7', models.IntegerField(choices=[(4, 'Muy útil'), (3, 'Relativamente útil'), (2, 'Moderadamente útil'), (1, 'Poco útil'), (0, 'Nada útil')], verbose_name='3.8.\tEl formulario F-EC7, de oferta formativa nacional sirvió de manera.')),
                ('sugpregunta_7', models.TextField(blank=True, null=True, verbose_name='Que sujiere?')),
                ('pregunta_8', models.IntegerField(choices=[(3, 'Buena Identificacion'), (2, 'Razonable identificación'), (1, 'Regular identificación'), (0, 'Deficiente identificación')], verbose_name='3.9.\tCon la aplicación de los instrumentos y metodología detallados anteriormente, se pudo identificar de manera cualitativa y cuantitativa la demanda del mercado profesional.')),
                ('pregunta_9', models.IntegerField(choices=[(3, 'Buena Identificacion'), (2, 'Razonable identificación'), (1, 'Regular identificación'), (0, 'Deficiente identificación')], verbose_name='3.10. Con la aplicación de los instrumentos y metodología detallados anteriormente se identificaron las principales áreas de desempeño profesionales, sus funciones….')),
                ('pregunta_10', models.IntegerField(choices=[(3, 'Buena Identificacion'), (2, 'Razonable identificación'), (1, 'Regular identificación'), (0, 'Deficiente identificación')], verbose_name='3.11. Con la aplicación de los instrumentos fuentes primarias y secundarias se pudo estructurar sistémicamente el proyecto curricular que responde a las exigencias y necesidades de la realidad actual.')),
                ('pregunta_11', models.IntegerField(choices=[(3, 'Buena Identificacion'), (2, 'Razonable identificación'), (1, 'Regular identificación'), (0, 'Deficiente identificación')], verbose_name='3.12. Con la aplicación de los instrumentos fuentes primarias y secundarias se pudo identificar las familias laborales en el rediseño curricular ')),
                ('pregunta_12', multiselectfield.db.fields.MultiSelectField(choices=[('i', 'Internet'), ('c', 'Computadora'), ('h', 'Hojas electrónicas'), ('s', 'Software estadístico'), ('o', 'Otros')], max_length=20, verbose_name='3.13. Que herramientas de apoyo y recolección de información se utilizó en esta etapa, para acceder a los colaboradores; selecciones varias opciones ')),
                ('pregunta_13', models.CharField(choices=[('b', 'Bueno'), ('o', 'Oportuno'), ('r', 'Regular')], max_length=2, verbose_name='3.14. Que calificación daría al equipo de gestión curricular en esta etapa.')),
            ],
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Jornada Académica)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Diagnostico Inicial)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Estudio de Contexto)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Mesa Multisectorial)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Macro Curricula)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_6',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Reunión Académica de la RAC)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_recurricular',
            name='netapa_7',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fc', 'Falta de compromiso de los estamentos'), ('nc', 'No se pudo conformar la comisión'), ('fr', 'Falta de recursos '), ('fa', 'Falta de asesoramiento técnico'), ('o', 'Otros')], max_length=20, null=True, verbose_name='Porque no realizó esta etapa? (Reunión Académica Nacional RAN)'),
        ),
    ]
