# Generated by Django 3.0.3 on 2020-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0009_auto_20200218_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa_3',
            name='opregunta_12',
            field=models.TextField(blank=True, null=True, verbose_name='Que otros?'),
        ),
    ]
