# Generated by Django 3.0.3 on 2020-02-19 12:37

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0010_etapa_3_opregunta_12'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapa_4',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('pregunta_1', models.BooleanField(verbose_name='4.2.\tSe cumplió toda la metodología planteada por el departamento de gestión curricular para llevar a cabo la reunión multisectorial.')),
                ('pregunta_2', models.CharField(choices=[('b', 'Buena'), ('ra', 'Razonable'), ('re', 'Regular'), ('d', 'Deficiente')], max_length=2, verbose_name='4.3.\tQue grado de comprensión se tuvo en la exposición de los resultados de contexto por el responsable académico (Director o Representante de la comisión).')),
                ('sugpregunta_2', models.TextField(blank=True, null=True, verbose_name='Que sugiere?')),
                ('pregunta_3', models.BooleanField(verbose_name='4.4.\tLa conformación de las mesas temáticas fue asignada en función de las familias laborales y de acuerdo a la necesidad del rediseño curricular.')),
                ('pregunta_4', multiselectfield.db.fields.MultiSelectField(choices=[('e', 'Expertos'), ('i', 'Instituciones'), ('a', 'Autoridades'), ('d', 'Docentes'), ('e', 'Estudiantes'), ('o', 'Otros')], max_length=20, verbose_name='4.5.\tLas mesas temáticas estaban conformadas por:')),
                ('opregunta_4', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_5', models.BooleanField(verbose_name='4.6.\tSe hizo una plenaria con los representantes de las diferentes mesas temáticas:')),
                ('pregunta_5_1', models.CharField(blank=True, choices=[('ex', 'Excelente'), ('b', 'Buena'), ('ra', 'Razonable'), ('re', 'Regular'), ('d', 'Deficiente')], max_length=2, null=True, verbose_name='4.6.1. El grado de la comprensión de la metodología empleada fue.')),
                ('pregunta_6', multiselectfield.db.fields.MultiSelectField(choices=[('nc', 'No se comprendió la metodología '), ('cp', 'Falta de compromiso de los participantes'), ('ac', 'No se pudo llegar a un acuerdo conjunto'), ('o', 'Otros')], max_length=20, verbose_name='4.7.\tQue dificultades se identificaron para aprobar y validar los resultados de las mesas temáticas en pleno por la sala:')),
                ('opregunta_6', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_7', models.CharField(choices=[('ad', 'Áreas de desempeño'), ('cg', 'Competencia Global'), ('np', 'Nodos problematizadores'), ('o', 'Otros')], max_length=2, verbose_name='4.8.\tSe realizó el fortalecimiento de cada una de las familias laborales en base a las:')),
                ('opregunta_7', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_8', models.CharField(choices=[('b', 'Bueno'), ('o', 'Oportuno'), ('r', 'Regular')], max_length=2, verbose_name='4.9.\tQue calificación daría al equipo de gestión curricular en esta etapa.')),
            ],
        ),
    ]
