# Generated by Django 3.0.3 on 2020-02-20 12:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0011_etapa_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapa_5',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('pregunta_1', models.BooleanField(verbose_name='5.2. Las familias laborales identificadas tienen correlación entre ellas y abastecen para contemplar todo lo necesario en la formación profesional.')),
                ('pregunta_2', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Buena'), (3, 'Razonable'), (2, 'Regular'), (1, 'Deficiente')], verbose_name='5.3.\tLa metodología para obtener la congruencia entre las familias laborales y el contexto sociocultural de la región y nacional fue:')),
                ('pregunta_3', models.IntegerField(choices=[(5, 'Muy útil'), (4, 'Relativamente útil'), (3, 'Moderadamente útil'), (2, 'Poco útil'), (1, 'Nada útil')], verbose_name='5.4.\tLa metodología empleada para identificar las competencias globales del perfil profesional académico de egreso es:')),
                ('pregunta_4', models.IntegerField(choices=[(5, 'Muy Adecuada'), (4, 'Adecuada'), (3, 'Neutral'), (2, 'Poco adecuada'), (1, 'Inadecuada')], verbose_name='5.5.\tLa metodología para obtener la pertenencia de las materias en las distintas familias laborales fue.')),
                ('pregunta_5', models.BooleanField(verbose_name='5.6.\tExistieron instancias participativas de retroalimentación (mejoras y modificaciones) de la Malla Curricular.')),
                ('pregunta_5_1', models.IntegerField(blank=True, choices=[(3, 'Alta'), (2, 'Media'), (1, 'Baja')], null=True, verbose_name='5.6.1. Qué grado de modificación se realizó en la retroalimentación.')),
                ('pregunta_6', models.BooleanField(verbose_name='5.7.\tSe realizó algún instrumento que denote el total de créditos, la distribución crediticia por área de formación y la proporción de horas teóricas y horas prácticas que estén dentro de los rangos recomendados.')),
                ('pregunta_6_1', models.IntegerField(blank=True, choices=[(5, 'Muy útil'), (4, 'Relativamente útil'), (3, 'Moderadamente útil'), (2, 'Poco útil'), (1, 'Nada útil')], null=True, verbose_name='5.7.1. Que tan importante fue el uso de este instrumento para para generar la malla curricular.')),
                ('pregunta_8', models.IntegerField(choices=[(5, 'Muy Adecuada'), (4, 'Adecuada'), (3, 'Neutral'), (2, 'Poco adecuada'), (1, 'Inadecuada')], verbose_name='5.9. La ubicación de las materias de acuerdo a las áreas de desempeño y familias laborales, de acuerdo a su grado de complejidad son:')),
                ('pregunta_9', models.CharField(choices=[('di', 'Digital en internet'), ('dc', 'Digital en una computadora'), ('h', 'Hojas foliadas'), ('nt', 'No tiene'), ('o', 'Otros')], max_length=2, verbose_name='5.10. Toda La documentación generada en el rediseño curricular esta etapa la tiene guardada en formato:')),
                ('opregunta_9', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_7', models.CharField(choices=[('b', 'Bueno'), ('o', 'Oportuno'), ('r', 'Regular')], max_length=2, verbose_name='5.11. Que calificación daría al equipo de gestión curricular en esta etapa.')),
            ],
        ),
        migrations.CreateModel(
            name='etapa_6',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('pregunta_1', models.IntegerField(choices=[(5, 'Muy Adecuada'), (4, 'Adecuada'), (3, 'Neutral'), (2, 'Poco adecuada'), (1, 'Inadecuada')], verbose_name='6.2.\tLa respuesta fue SI. aplicar las siguientes preguntas La aplicación de normativas vigentes establecidas en la Reunión Académica de Carrera fue:')),
                ('pregunta_2', models.BooleanField(verbose_name='6.3.\tPara la validación de los informes anteriores se realizó en una RAC (pre sectorial).')),
                ('pregunta_3', models.CharField(choices=[('in', 'Institucional'), ('a', 'Académica'), ('iv', 'Investigación'), ('ex', 'Extensión e interacción social'), ('P', 'Postgrado'), ('o', 'Otros')], max_length=2, verbose_name='6.4.\tEn la RAC (pre sectorial) que tipo de comisiones se conformaron.')),
                ('opregunta_3', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_4', models.IntegerField(choices=[(3, 'Alta'), (2, 'Media'), (1, 'Baja')], verbose_name='6.5.\tEl grado de aporte en la RAC (pre sectorial) del sector docente')),
                ('pregunta_5', models.IntegerField(choices=[(3, 'Alta'), (2, 'Media'), (1, 'Baja')], verbose_name='6.6.\tEl grado de aporte en la RAC (pre sectorial) del sector estudiantil')),
                ('pregunta_6', models.CharField(choices=[('n', 'Normas'), ('po', 'Procesos'), ('pi', 'Principios'), ('fo', 'Fines y objetivos de la Universidad'), ('o', 'Otros')], max_length=2, verbose_name='6.7.\tCuáles son las bases en las que se fundamentaron para llevar a cabo la RAC (pre sectoriales)')),
                ('opregunta_6', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_8', multiselectfield.db.fields.MultiSelectField(choices=[('b', 'Computadora'), ('c', 'Celular'), ('d', 'Data Display'), ('o', 'Otros')], max_length=20, verbose_name='6.9.\tQue herramienta digital utilizó para organizar la información en esta etapa.')),
                ('opregunta_8', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
                ('pregunta_7', models.CharField(choices=[('b', 'Bueno'), ('o', 'Oportuno'), ('r', 'Regular')], max_length=2, verbose_name='6.10. Que calificación daría al equipo de gestión curricular en esta etapa.')),
            ],
        ),
        migrations.CreateModel(
            name='etapa_7',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('pregunta_1', models.BooleanField(verbose_name='7.2.\tSe cumplió con todos los requisitos para presentar a la Reunión Académica Nacional.')),
                ('pregunta_2', models.CharField(choices=[('a', 'Aplicados'), ('fr', 'Pospuestos por falta de recursos'), ('ne', 'No tomados en cuenta'), ('pc', 'En proceso de corrección'), ('o', 'Otros')], max_length=2, verbose_name='7.3.\tLas recomendaciones que hizo la Reunión Académica Nacional en su informe fueron.')),
                ('opregunta_2', models.TextField(blank=True, null=True, verbose_name='Que Otros?')),
            ],
        ),
    ]
