# Generated by Django 3.0.3 on 2020-03-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0014_historicaletapa_1_historicaletapa_2_historicaletapa_3_historicaletapa_4_historicaletapa_5_historical'),
    ]

    operations = [
        migrations.CreateModel(
            name='participantes',
            fields=[
                ('evaluacion_recurricular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='redicurri.evaluacion_recurricular')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('ci', models.PositiveIntegerField()),
            ],
        ),
    ]
