# Generated by Django 3.0.3 on 2020-03-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0015_participantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='participantes',
        ),
    ]
