# Generated by Django 3.0.3 on 2020-03-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redicurri', '0018_historicalparticipantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipantes',
            name='estamento',
            field=models.CharField(choices=[('e', 'Estudiante'), ('d', 'Docente')], default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantes',
            name='estamento',
            field=models.CharField(choices=[('e', 'Estudiante'), ('d', 'Docente')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
